version: 0.2
env:
  git-credential-helper: yes
cache:
  paths:
    - '/root/.cache/pre-commit/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.ssh/ci_scripts'
phases:
  install:
    runtime-versions:
       nodejs: 12
    commands:
      - npm install next react react-dom
  # pre_build:
  #  commands:
  #   - pre-commit run -a
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # - zip -r eb_deployment.zip .next package.json
      - mkdir deploy
      - mv ./.next deploy/.next
      - mv ./package.json dpeloy/package.json
      # - aws s3 cp eb_deployment.zip s3://codepipeline-us-west-2-472569803885/sinjury-website-code/SourceArti/
      # Abortar si falla la fase build
artifacts:
  files:
    - ./deploy/*
